version: "3"

services:
  dashboard:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${APP_PORT:-80}:80"
    networks:
      - admin_app_network


networks:
    admin_app_network:
        driver: bridge
        external: true
